### ISSUE TITLE
Rendre les types de prestation paramétrables

### ISSUE THREAD

**Issue by thomas-bouvier** [n7consulting/Incipio#145]
Lors de la rédaction de l'avant-projet, les choix associés au type de prestation ne sont pas paramétrables. Ceux-ci devraient pouvoir être édités par l'utilisateur.

Beau travail en tout cas ;)

**Comment by Stoakes** [comment]
@Olivier-R

Est ce que vous utilisez/pensez utiliser ce champ chez M-Gate ? 

Parce que nous pas du tout. Du coup au lieu de le modifier, on pourrait peut être juste le supprimer.

 Plusieurs arguments iraient dans ce sens : 
 * Aucune statistique n'y est associé
 * Il ne sert qu'a un seul endroit
 * Il semble lié à la forme de votre doctype lorsqu'Incipio fut créé.

**Comment by Olivier-R** [comment]
Non on ne s'en sert pas, je trouvais aussi que ça faisait doublon avec le domaine de compétence.

**Comment by Olivier-R** [comment]
#SelfAssign

**Comment by Stoakes** [comment]
Est-ce que tu as moyen de faire ça ce week-end ou pas ? 
J'aimerais bien release la 2.4 le week-end prochain, donc feature freeze ce week-end.
