### ISSUE TITLE
Factoriser le code du formulaire d'une etude

### ISSUE THREAD

**Issue by Stoakes** [n7consulting/Incipio#154]
Il y a beaucoup de code similaire entre `src/Mgate/SuiviBundle/Resources/views/Etude/ajouter.html.twig` et `src/Mgate/SuiviBundle/Resources/views/Etude/modifier.html.twig`.

Dans le même temps, `src/Mgate/SuiviBundle/Resources/views/Etude/formulaire.html.twig` est quasiment vide et inutilisé. Il serait simple de factoriser le code des formulaires d'une étude en un seul fichier.

**Comment by Olivier-R** [comment]
#SelfAssign
