### ISSUE TITLE
Le document type AP n'est pas correctement installé

### ISSUE THREAD

**Issue by Stoakes** [n7consulting/Incipio#175]
Lors d'une installation standard, le document type AP fourni ne fonctionne pas.

Par contre le télécharger depuis github, l'importer puis exporter un AP fonctionne.

Pire que ça, prendre le document depuis l'espace d'admin et le ré-uploader dans jeyser fonctionne.

**Comment by Olivier-R** [comment]
A l'importation, des manipulations sont effectuées sur le document, ça peut venir de là

**Comment by Stoakes** [comment]
Ca à l'air de venir de là, mais je ne vois pas quelle modification est faite sur le contenu du document et qui expliquerait cette différence de comportement.

**Comment by Olivier-R** [comment]
Ce sont des modifications au niveau du xml lors de l'upload, il faut unzip les documents pour les voir

**Comment by Stoakes** [comment]
My bad je regardais la mauvaise méthode. :cry: 

Ok, je vois. Tu veux fixer ça ou je le gère ?

**Comment by Olivier-R** [comment]
Je m'en charge
