### ISSUE TITLE
Bug datepicker mission

### ISSUE THREAD

**Issue by Olivier-R** [n7consulting/Incipio#186]
Pour une étude, quand on rédige les RM des intervenants, la date de début de mission est automatiquement remplie.

Si on la modifie avec le datepicker elle est fausse dans la vue des RM des intervenants. Le format semble correct mais en BDD le champ est de type datetime et je ne sais pas pourquoi le mois est transformé en heure...
Le datepicker fonctionne correctement par exemple pour saisir/modifier la date de naissance d'un membre mais le type en BDD est date.

Suggestion: modifier le type en BDD et vérifier le format des datepicker (+ format fr)

**Comment by Stoakes** [comment]
Effectivement.

Ca t'a été remonté récemment (régression récente) ou c'est ancien ?
