### ISSUE TITLE
Contraintes sur l'entité Phase

### ISSUE THREAD

**Issue by Stoakes** [n7consulting/Incipio#187]
L'entité Phase n'a aucune contrainte.

Ce qui permet de créer des Phases sans délai, prix .... Une phase sans délai lève notamment une erreur (en dev) pour le calcul de la date de fin d'une étude.

Y a t-il encore une raison pour laquelle une phase peut avoir un nombre de JEH vide, un nombre de jour de travail vide ?

Historiquement, l'ajout des phases était en 2 temps: un POST pour créer un squelette de phase vide, un POST pour valider les modifications de ce squelette, d'où la possibilité d'avoir des valeurs nulles.

**Comment by Olivier-R** [comment]
Tout à fait, il faut des contraintes sur les phases.
Il faut pouvoir faire des phases à 0 JEH mais un prix de JEH toujours dans la fourchette 80-340.
L'inverse (une phase avec des JEH à 0€) est interdit.

**Comment by Stoakes** [comment]
Pourquoi permettre des phases à 0 JEH ?

Par contre la contrainte de la fourchette 80 340 est-elle vraiment nécessaire ? 
 * Nous nous mettons des phases avec  un nombre de jour négatif (ou un prix négatif, ça dépend des gens) lors d'un avenant réduisant le nombre de phase.
 * Je n'aime pas l'idée de coder en dur des contraintes dans Jeyser. Ca introduit une maintenance obligatoire en cas de changement de législation.

**Comment by Olivier-R** [comment]
Des phases à 0 JEH ça peut arriver pour des élements que tu ne factures pas forcément au client, par exemple lors d'un geste commercial.
La contrainte de la fourchette est importante car sinon c'est hors qualité à l'audit si je ne me trompe.
Une autre solution que vérifier à la saisie que la valeur est contrainte par rapport à des valeurs paramétrables ?

**Comment by Stoakes** [comment]
Les situations possibles étant apparemment multiples, je propose de prendre la solution la plus légère: uniquement une contrainte sur le délai (@Assert\NotNull) et c'est tout.
