### ISSUE TITLE
Suggestion base de données

### ISSUE THREAD

**Issue by Olivier-R** [n7consulting/Incipio#211]
Est-ce qu'il y aurait un intérêt de stocker certaines informations communes dans une base de données type Firebase ?
On pourrait y mettre un changelog; les J.E. utilisatrices pour faire une carte; des évènements pour un calendrier; les valeurs par défaut actualisées de base URSSAF et cotisations...
Il pourrait y avoir ensuite une copie locale.

**Comment by theofidry** [comment]
Est-ce qu'il y a le moindre intérêt/besoin d'utiliser une base de donnée de type Firebase?

Quant à centraliser les données de plusieurs J.E., cela pose plusieurs problèmes niveau confiance, sécurité et responsabilités.

**Comment by Stoakes** [comment]
Je ferme cette suggestion.

Comme l'a souligné Théo, centraliser des infos pose différents problèmes. Quelques exemples pour illustrer:
 * En cas de vulnérabilité dans Jeyser, un registre des versions utilisées par les différentes juniors rend les attaques plus faciles. 
 * En cas de disparition d'une personne du projet, quid du maintien de cette base de données ? Rendre un service dégradé, n'est pas envisageable.

Enfin, centraliser des infos n'est pas dans la philosophie du projet. Nous souhaitons redonner aux juniors-entreprises le plein contrôle de leur système d'information, et surtout pas introduire des points potentiellement bloquants.

C'est aussi pour cette raison que nous n'entretenons pas un dépôt sur le dockerhub. En cas de disparition du projet, la qualité de fonctionnement de Jeyser ne devrait pas être dégradée.
