### ISSUE TITLE
Ajouter l'application de la GDPR

### ISSUE THREAD

**Issue by Stoakes** [n7consulting/Incipio#234]
Je vois le module de la forme suivante

 * une page d'accueil avec un formulaire: sélection du nom de la personne, un bouton par droit fondamental de la gdpr. Valider ce bouton renvoie vers la page associée.
 * Il ne sera pas possible de réellement supprimer le compte dans le cas où la personne à signé des documents. Cela casserait la cohérence des données. Je propose donc au lieu de cela d'anonymisé les données qui doivent rester.

Exemple: Jean Dupont demande à être supprimé de la base de donnée, mais à signé toute une étude en  2016. Au lieu de supprimer l'entrée Jean Dupont de la table des personnes (rendant ainsi de nombreux champs invalides), changer toutes les données personnelles de Jean Dupont par "Anonyme0X" avec X une variable entière aléatoire.

@Olivier-R est ce que le module tel que décrit ici te semble ok ? est ce que tu as des suggestions supplémentaires ?

**Comment by Olivier-R** [comment]
Est-ce que le processus ne devrait pas être automatisé pour garantir que sa demande est traitée dans les temps ?
Je vois deux possibilités :
- Jean Dupont peut depuis son compte le supprimer, ça applique automatiquement la GDPR
- Quelqu'un avec le ROLE_GDPR peut depuis le menu l'appliquer à n'importe qui

Dans les 2 cas on peut supprimer toutes ses données personnelles s'il n'a pas fait d'études, sinon on ne garde que les données personnelles présents dans les "contrats" ?

**Comment by Stoakes** [comment]
La mise en place d'une automatisation ne me semble pas possible. Pour les membres se serait vaguement envisageable, mais comment faire pour les employés des clients ? Nous n'avons aucun moyen de les identifier, ni de leur donner un accès à Jeyser.

Enfin, plus sur l'essence du projet, de mon point de vue, Jeyser est un outil pour simplifier la vie des juniors-entreprises, pas pour pallier à ses failles. Si la junior n'est pas capable de trouver les ressources pour appliquer la loi, j'ai envie de dire, tant pis.

Nous ne garderons aucune donnée personnelle. Mais dans le cas d'un contrat, tout sera anonymisé pour respecter la loi, sans détruire l'étude en entier (ce qui est l'alternative si les données devaient être détruite).

Je commence un prototype cette semaine.
