### ISSUE TITLE
Bug date négative phase

### ISSUE THREAD

**Issue by PitouGames** [n7consulting/Incipio#246]
Il est possible d'enregistrer une phase avec une date négative comme délai. (http://jeyser-demo.herokuapp.com/suivi/phases/modifier/1)
Il est ensuite impossible de retourner à l'étude, l'utilisateur obtient une erreur 500.

C'est arrivé à un membre de la JE qui ne savais pas encore quelle valeur mettre. Pour débloquer la situation, je suis passé par le lien direct d'édition de la phase qui par chance fonctionnait toujours. "/suivi/phases/modifier/7" et j'ai remis une valeur positive.

**Comment by Stoakes** [comment]
Salut,

Merci pour le rapport de bug.

Mettre un délai négatif est normal, notamment pour réduire le délai d'une étude (dans le cas d'un avenant par exemple). Par contre l'erreur 500 ne l'est pas.

Je regarde ça.
