### ISSUE TITLE
Date dernière connexion utilisateurs

### ISSUE THREAD

**Issue by PitouGames** [n7consulting/Incipio#247]
Sur la page de la liste des utilisateurs (http://jeyser-demo.herokuapp.com/user/lister), la date de dernière connexion d'un membre n'ayant jamais utilisé son compte est mis à la date et heure actuelle (ce qui est trompeur).
Il serait préférable d'afficher un message du type "Jamais" ou "Cet utilisateur ne s'est jamais connecté"

**Comment by Stoakes** [comment]
En effet.

Est-ce que ça t'intéresse d'essayer de le corriger ? C'est facile, il suffit de modifier [UserBundle/lister.html.twig](https://github.com/n7consulting/Incipio/blob/master/src/Mgate/UserBundle/Resources/views/Default/lister.html.twig).

D'ailleurs pour rester dans l'idée de la page, je mettrais plutôt un - qu'un texte.

Si tu es motivé, tu peux même faire une PR contenant ce bugfix et #245 (au moins la partie design). Qu'en dis tu ?

**Comment by PitouGames** [comment]
Oui, ça m’intéresse de mettre la main à la pâte.
J'ai déjà trouvé comment corriger cette issue grâce à ton indication 👍 

Je vais maintenant regarder l'issue #245  😄
