### ISSUE TITLE
Erreur de suppression d'un membre avec documents liés

### ISSUE THREAD

**Issue by PitouGames** [n7consulting/Incipio#276]
Lorsqu'un étudiant a des documents qui lui sont liés, la suppression du membre devient impossible.
L'erreur levée est :
`An exception occurred while executing 'DELETE FROM RelatedDocument WHERE id = ?' with params [2]: SQLSTATE[23503]: Foreign key violation: 7 ERROR: update or delete on table "relateddocument" violates foreign key constraint "fk_211fe8203256915b" on table "document" DETAIL: Key (id)=(2) is still referenced from table "document".`
J'ai l'impression qu'il y a un "?" à la place de l'id du document qui doit aussi être supprimé.

Cette erreur est très semblable à #219

**Comment by Stoakes** [comment]
Le ? est remplacé par l'id du document lorsque la requête préparée est exécutée.

Par contre il y a avait une clé étrangère qui bloquait la suppression, ce qui est maintenant corrigé.
