### ISSUE TITLE
Impossible de supprimer une étude

### ISSUE THREAD

**Issue by PitouGames** [n7consulting/Incipio#293]
Une étude de test a été crée par des membres de ma JE pour découvrir l'outil.
Lorsque nous voulons la supprimer, nous obtenons une erreur 500 sur la page `/suivi/etude/supprimer/{NOM ETUDE}`
L'erreur est 

> 500 Internal Server Error
>
>An exception occurred while executing 'DELETE FROM Etude WHERE id = ?' with params [23]: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`incipio`.`Etude`, CONSTRAINT `FK_DC1F8620904F155E` FOREIGN KEY (`ap_id`) REFERENCES `Ap` (`id`))

Cette erreur me donne l'impression que l'AP n'est pas supprimé en BDD avant que l'étude le soit. Je n'ai pas plus d'éléments sur ce bug pour le moment. Je n'ai pas réussi à le reproduire sur la version de démo de Jeyser, car je n'arrive pas à générer un AP sur la démo (champs vides mais avec aucune proposition possible).

**Comment by PitouGames** [comment]
J'ai réussi à recréer le bug sur mon installation perso, mais pas sur la démo :
- Créer un nouvelle étude, rentrer des valeurs bidon
- Valider la création en cliquant sur "Enregistrer et passer à l'AP"
- Pour l'AP, mettre des valeurs uniquement dans les champs "date de signature" et "compétences"
- Cliquer sur "Enregistrer l'AP"
- Essayer de supprimer l'étude

Mon installation perso tourne sous docker et a été installée en suivant à la procédure officielle, à partir de la version 2.7.0
J'ai l'impression que le schéma de ma bdd est différent de celui que je deverai avoir, or mon installation est récente... Il y a quelque chose qui m'échappe.

**Comment by Stoakes** [comment]
Merci pour la procédure de reproduction du bug.

Pour la synchronisation des schémas, il y a peut être une différence entre le schéma créé par les migrations et le schéma attendu (notamment avec le passage à la gestion du schéma de bdd avec uniquement des migrations en 2.7.0).

Est ce que la commande `php bin/console doctrine:schema:update --dump-sql` te retourne une requete ?

**Comment by Stoakes** [comment]
Mettre à jour vers la version 2.8.0 devrait corriger le problème.
