### ISSUE TITLE
erreur import BDD SIAJE

### ISSUE THREAD

**Issue by Yirmandias** [n7consulting/Incipio#297]
Lorsque j'essaie d'importer une BDD SIAJE depuis un fichier CSV, j'obtiens cette erreur.

![image](https://user-images.githubusercontent.com/43903075/54355909-98702c80-465a-11e9-908b-7e1f1a4de317.png)

request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Undefined class constant 'EXPECTED_FORMAT'" at /app/src/Mgate/PubliBundle/Manager/CsvImporter.php line 28 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Undefined class constant 'EXPECTED_FORMAT' at /app/src/Mgate/PubliBundle/Manager/CsvImporter.php:28)"} {"url":"/Documents/import","ip":"172.18.0.2","http_method":"POST","server":"crm.juniorinsaservices.fr","referrer":"https://crm.juniorinsaservices.fr/Documents/import"}

Est-ce que vous avez déjà rencontré cette erreur?

**Comment by Stoakes** [comment]
Bonjour,

Le module d'import est très peu utilisé. Pour ne rien cacher, j'avais oublié son existence jusqu'à ton message. Du coup il n'est pas maintenu /testé et c'est un bug. 

Je vais corriger ça.

**Comment by Yirmandias** [comment]
Merci beaucoup! Est-ce que tu as une idée de quand ça sera réglé?

**Comment by Stoakes** [comment]
Je ne sais pas, je suis partagé entre: 
 * Livrer ça avec la version 3.0, mais ça risque d'arriver mi-Mai
 * Faire un patch v2.8.1 qui ne contient que ça, mais il faudra le ramener dans master après, et c'est un peu pénible.

Vous comptez dessus pour importer des données ?

D'ailleurs, est-ce que tu as toujours le squelette du fichier fourni par siaje (avec des fausses données) ? Je n'ai pas réussi à le retrouver dans mes archives.

**Comment by Yirmandias** [comment]
Effectivement on compte dessus pour importer nos données. On a 280 lignes donc à la main c'est un enfer...
Mi-Mai c'est un peu tard pour nous.
Je vais essayer de trouver ça, je n'en ai pas à te fournir pour le moment.

**Comment by Yirmandias** [comment]
[squelette_siaje_etudes.xlsx](https://github.com/n7consulting/Incipio/files/3014178/squelette_siaje_etudes.xlsx)
Voilà ce que j'ai pu trouver.

**Comment by Stoakes** [comment]
Merci.

Est-ce que tu pourrais me donner le fichier squelette avec au moins une ligne de données s'il te plait ? Ca me permettrait de reproduire le problème, car actuellement comme le squelette ne contient aucune donnée je n'arrive pas à reproduire l'erreur (par exemple sur la démo, l'import fonctionne correctement alors qu'il ne devrait pas)

Si ça vous impacte, ok pour patcher ça et sortir une version 2.8.1 rapidement.

**Comment by Yirmandias** [comment]
Ok, je vais créer une ligne fictive!

**Comment by Yirmandias** [comment]
Je n'arrive pas à importer un fichier csv sur github.

**Comment by Yirmandias** [comment]
[squelette_siaje_etudes.xlsx](https://github.com/n7consulting/Incipio/files/3025600/squelette_siaje_etudes.xlsx)
Voilà une ligne dans un format .xlsx
J'espère que ça te suffira!

**Comment by Yirmandias** [comment]
Je viens d'essayer qqch : en format xlsx, il n'y a plus d'erreurs avec les fichiers. Par contre il n'importe aucune donnée
![image](https://user-images.githubusercontent.com/43903075/55277787-3ffc8880-5304-11e9-83f4-ff615fb39237.png)

**Comment by Stoakes** [comment]
Salut,

#299 contient le patch pour le problème + quelques améliorations sur l'import depuis Siaje.

Je l'ai testé avec le fichier [siaje.zip](https://github.com/n7consulting/Incipio/files/3099934/siaje.zip) (le zip contient juste un fichier csv car Github ne supporte pas l'upload de fichier csv).

J'aimerais bien que vous testiez de votre coté avant de merger et de faire une release avec. Est-ce que vous avez moyen de tester le patch de votre coté ?

**Comment by Stoakes** [comment]
Finalement la version 2.8.1 va sortir aujourd'hui et contiendra le patch #299.

Il y a une série de patch de sécurité qui viennent de sortir sur Symfony, donc je vais produire la version 2.8.1 pour les rendre disponibles à toutes les installations de Jeyser et ne pas attendre votre retour.

**Comment by Yirmandias** [comment]
Salut, 

Merci bcp pour le patch. Je ne vois pas encore que l'on peut mettre à jour jeyser, mais j'imagine qu'il faut que le pull request soit validé par d'autres?
Nous n'avons qu'un seul serveur jeyser dans notre JE, il aurait fallu que je l'installe sur un autre PC mais je n'ai pas accès à ces ressources pour le moment.

**Comment by Stoakes** [comment]
Ok, je viens de release la version 2.8.1. Vous pouvez mettre à jour.
