### ISSUE TITLE
Champs doc type

### ISSUE THREAD

**Issue by Yirmandias** [n7consulting/Incipio#301]
Mon équipe est actuellement en train de créer le doc type pour pouvoir utiliser Jeyser.
Est-ce qu'il y a un endroit pour trouver tous les champs utilisables?
Merci par avance

**Comment by Stoakes** [comment]
Bonjour,

Non il n'y a pas de tel document. Le seul moyen est d'explorer le code de Jeyser ou d'utiliser ceux des documents types d'exemples.

Voici quelques détails qui pourraient toutefois t'aider:

Les champs disponibles pour un objet (une étude, un membre ...) sont les fonctions (équivalent à méthodes) publiques de cet objet. Par exemple, les champs disponible pour l'objet étude sont disponibles à https://github.com/n7consulting/Incipio/blob/master/src/Entity/Project/Etude.php

`public function getReference` ou `getDateLancement` sont des fonctions publiques. Elles peuvent donc être utilisée dans les doctypes. D'ailleurs pour info `{{ etude.reference}}` et `{{etude.getReference}}` donneront le même résultat.


Chaque champ à un type qui conditionne son utilisation. Ces champs peuvent être:
 * un autre objet (CC, Ap), et dans ce cas, tu peux te reporter à leur code pour continuer l'exploration.
 * un tableau d'autres objets (RMs, Phases), dans ce cas il est possible de faire une boucle sur ce tableau pour accéder à ces objets.
 * Une date. Le système de template propose de nombreuses fonctions autour des dates.
 * Un "type de base" (dans le sens PHP) tel un nombre, un texte.

N'hésites pas si tu as d'autres questions ou si des points ne sont pas clair.

**Comment by Yirmandias** [comment]
Ok je vais regarder le code.

Néanmoins j'ai une question concernant le planning gantt. Dans l'AP il est exporté directement dans le doc word. Quel est le champ qu'il faut mettre pour pouvoir l'utiliser?

**Comment by Stoakes** [comment]
C'est un peu expérimental et ça ne fonctionne pas chez tout le monde.
La méthode la plus fiable est d'exporter l'image et de la coller dans le document. 

Sinon,vous pouvez essayer ça:
 * L'export de Gantt ne fonctionne que sur le document-type AP
 * Importez dans le doctype une image servant d'espace réservé, aux dimensions souhaitées pour le Gantt. Le nom de fichier de cette image doit obligatoirement être `imageVARganttAP.png`

Ca m'intéresse de connaitre le résultat, si tu as réussi à le faire marcher sur un de tes doctypes.

**Comment by Yirmandias** [comment]
ça n'a pas fonctionné. On se débrouille en le rajoutant à la main. Merci de ton aide!
