### ISSUE TITLE
Jeyser 3 : Erreurs multiples en tréso

### ISSUE THREAD

**Issue by PitouGames** [n7consulting/Incipio#306]
Sur mon installation perso de Jeyser 3 (master actuel), j'ai plusieurs pages de la partie tréso qui me retournent des erreurs diverses, voici la liste :
-  /Tresorerie/Facture/Ajouter
-  /Tresorerie/NoteDeFrais/Ajouter
-  /Tresorerie/Declaratifs/TVA
-  /Tresorerie/Declaratifs/BRC

Si vous pouvez vérifier que c'est aussi votre cas. Elles sont à corriger et ajouter les tests d'accès aux pages. Je pourrais éventuellement m'en occuper.

**Comment by Stoakes** [comment]
La première partie, corriger les problèmes, est dispo sur la PR #307
