### ISSUE TITLE
Problem with comments

### ISSUE THREAD

**Issue by Yirmandias** [n7consulting/Incipio#311]
Bonjour, nous avons un problème avec les commentaires dans les études et pour les prospects sur la version 2.8.1. Lorsqu'on essaie de poster des commentaires, ils semblent disparaitre. Voilà ce que ça donne : 
![image](https://user-images.githubusercontent.com/43903075/66217237-38f56f00-e6c7-11e9-9d25-a1fbb9391d9e.png)

**Comment by Yirmandias** [comment]
Est-ce que vous avez trouvé une solution?

**Comment by Stoakes** [comment]
Bonjour,
Je confirme que les commentaires fonctionnaient en 2.7.0 et qu'ils sont cassés sur master. Je regarde ça et essaie de produire un correctif d'ici mi-janvier.

**Comment by Stoakes** [comment]
Le problème vient de la restriction des contenus mixtes (d'un point de vue HTTPS):

Copie de la console développeur Chrome lorsque l'on essaie de poster un commentaire:
```
Mixed Content: The page at 'https://crm.n7consulting.fr/prospect/voir/28#tab4' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://crm.n7consulting.fr/api/threads/prospect_28/comments'. This request has been blocked; the content must be served over HTTPS.
send @ jquery-1.12.0.min.js:4
```

**Comment by Stoakes** [comment]
Le correctif de ce problème à été mergé dans master et une version `v3.0.0-alpha.2` sera disponible dans les prochains jours. Il faudra mettre à jour vers cette version pour corriger le problème dans votre installation.

*Note:* La version 3.0.0 est encore taggée alpha.X car il manque encore des fonctionnalités avant d'officiellement produire une version 3.0.0. Elle est cependant suffisamment stable pour être utilisée au jour le jour (et c'est la version qu'N7 Consulting utilise depuis plusieurs mois déjà).
