### ISSUE TITLE
Installation sur serveur auto-hébergé

### ISSUE THREAD

**Issue by bastiencyr** [n7consulting/Incipio#331]
Bonjour, 

Je suis actuellement dans une JE (PSI à strasbourg) et j'aimerais essayer ce logiciel. 

J'ai suivi la procédure d'installation mais je pense que ça bloque à cause d'autres logiciels installés sur le serveur (Nextcloud avec Nginx et Onlyoffice). En listant les images docker lancées (docker ps), trois sont lancés.
En regardant un peu la configuration docker, je me rends compte que le serveur http Traefik n'a pas pu être lancé car il écoute sur des ports déjà utilisés. 

Edit : Je viens de lire ça sur votre site

>  "In the following steps, we assume that your server will be used to run only Jeyser. If it is not the case, please refer to the FAQ"

Mais je n'ai rien trouvé dans le FAQ

Voilà, avez-vous une solution ?

**Comment by Stoakes** [comment]
Bonjour,

Bienvenue.

L'installation de Jeyser sur un serveur partagé avec d'autres applications a été supprimée de la FAQ car elle techniquement est plus complexe et a généré de long threads de mail de support (et donc le temps qui va avec) pour une installation moins robuste et pour finalement économiser 3€/mois (le prix d'un VPS entrée de gamme).

C'est pourquoi il n'y a plus d'aide pour installer Jeyser sur un serveur partagé.

Si vous avez le niveau technique pour :
 * Désactiver Traefik
 * Configurer le reverse proxy exposant vos services pour router le traffic vers le container Apache faisant tourner Jeyser
 * Configurer le SSL pour exposer Jeyser en toute sécurité

c'est super, je vous encourage à le faire (et à le documenter pour vos mandats suivants). 

Si ce n'est pas possible vous pouvez essayer de [faire tourner Jeyser en local](https://jeyser-crm.n7consulting.fr/docs/dev/local-development/) ou ouvrir un compte chez un hébergeur, (il existe même des packs étudants [Github student pack](https://education.github.com/pack) qui offrent des crédits gratuits)

**Comment by bastiencyr** [comment]
Salut,
Merci pour ta réponse et ton aide :) 
Arf, en prenant un peu de temps, je pourrai y arriver mais je ne suis pas fan des solutions maisons. 

Sinon, rien à voir mais si j'arrive à faire adopter Jeyser dans mon asso (et c'est bien parti), je vais aussi les pousser à créer un poste permanent dans la JE pour prendre part au projet Jeyser. Dans ce cas-là, ce serait possible d'avoir un peu d'aide de votre part pour comprendre l'architecture du projet tout ça tout ça.

Merci :)

**Comment by Stoakes** [comment]
Ok.

Ca serait une bonne nouvelle. Et oui, pas de problèmes pour discuter Jeyser et aider à le comprendre/le prendre en main.

Je ferme le ticket car le problème de base est résolu, mais on peut continuer à discuter.
