### ISSUE TITLE
Problème pour générer un avenant d'une convention d'étude

### ISSUE THREAD

**Issue by Tay18** [n7consulting/Incipio#332]
Bonjour,

Je suis Chef de projet au sein de la MOMA Junior Conseil. J'ai voulu générer un avenant pour une convention d'étude mais un message d'erreur apparait : 

500 Internal Server Error
Unexpected "}" in "__string_template__fa9814e12f25344244af4720590f7462f416b4e2c55380ef4608bdaab68e6de6" at line 1.

Je vous remercie par avance de l'intérêt que vous allez porter à ma requête.

Tayeb Sihida
Chef de projet - MOMA Junior Conseil
tayeb.sihida@momaconseil.com

**Comment by Stoakes** [comment]
Bonjour,

Cette erreur vient probablement d'un template mal formé: la syntaxe du document type n'est pas valide et un `}`  est en trop, ce qui fait planter le parseur.

Vous pouvez :
 1. Relire le document type pour voir si toutes les `{{` sont correctement fermées via `}}`.
 2. Vérifier qu'il n'y a pas de d'accolades fermantes surnuméraire.

Si cette relecture n'est pas suffisante, il existe un [moyen de déterminer précisément la source du problème](http://jeyser-crm.n7consulting.fr/docs/features-fr/documents-types-faq/#apr%C3%A8s-export-mon-document-est-corrompu-), mais il est plus technique donc commençons par une simple relecture.
