### ISSUE TITLE
Accéder au champ étude depuis la page de modification d'une facture

### ISSUE THREAD

**Issue by KiDayz** [n7consulting/Incipio#335]
J'ai dev un petit fix pour pouvoir accéder au champ "étude" lors de la création/modification d'une facture. Y-a-t-il des procédures / best practices particulières à prendre avant de faire pusher le change ?

J'en profite : je voulais faire des tests en environnement de dev sur la génération de doctype, mais ni l'ajout de doctype ni la génération de doctype ne fonctionne. J'ai cru lire que c'était dû au fait que j'étais en dev, mais je n'arrive pas à retrouver où c'était. Avez-vous plus d'infos par rapport à cela ?

**Comment by Stoakes** [comment]
Bonsoir,

Pas de procédure particulière, il faut uniquement ouvrir une PR vers la branche master de [n7consulting/Incipio](https://github.com/n7consulting/Incipio). 
La CI te guidera s'il y a des choses à corriger: code à linter, tests qui échouent ...

Pour la génération des doctypes, quelles erreurs as tu ? (Je viens de tester en local et effectivement ça ne marche pas du premier coup, il y a donc peut être un peu de config à modifer).

**Edit**, si d'est un problème du type `dossier tmp/ doesn't exist`, la solution de contournement est d'exécuter les commandes suivantes:

```bash
docker-compose exec web mkdir public/tmp
docker-compose exec web chown www-data public/tmp
```

En règle générale, en mode dev, la génération des doctypes est un peu plus compliquée. Symfony ne laisse pas passer les erreur de type warning ou notice et la génération échoue la plupart du temps.

Voici une solution de contournement pour tester la génération de doctypes (je te laisse l'ajouter dans la documentation développeur Jeyser 😉): passer en mode prod le temps de tester les documents types. 

Pour ce faire:

 1. Sur une installation fonctionnelle de Jeyser, éditer `.env` et remplacer `APP_ENV=dev` par `APP_ENV=prod`
 2. Recréer le container web: `docker-compose up -d web`
 3. Rafraichir la page de Jeyser, la barre de développement en bas devrait avoir disparue
 4. Lancer la génération du doctype.

Une fois les tests terminés, tu peux repasser l'application en mode dev en éditant à nouveau `.env` et recréant le container.

*Bonus: commande linux pour passer en mode prod sans édition manuelle*

`sed -i 's/APP_ENV=dev/APP_ENV=prod/g' .env && docker-compose up -d web`

**Comment by KiDayz** [comment]
Ok super, merci pour toutes ces infos :)
