### ISSUE TITLE
Les AP et CC -> encore d'actualité ?

### ISSUE THREAD

**Issue by KiDayz** [n7consulting/Incipio#336]
Bonsoir, 

Dans un soucis d'être le plus général possible (dans le sens utilisable par toutes les JEs cf. la documentation) : 
Les AP et CC sont utilisés partout dans Jeyser, notamment dans le calcul des indicateurs. C'est là que cela devient problématique car les CE, elles, ne sont pas prises en compte dans le calcul des indicateurs.

Tout le monde devrait être passé en duo Devis / CE depuis l'AGP qui date de plusieurs années.

Je travaille sur un fix et je vois deux solutions : 
#### Solution 1 - prendre en compte les CC ET les CE
Cela prendra plus de temps mais sera plus général

#### Solution 2 -prendre uniquement en compte les CE
Plus rapide, moins général mais tout le monde devrait être passé en Devis/CE...

Quelles sont vos préconisations ?

**Comment by Stoakes** [comment]
Bonjour,

Jeyser doit rester rétro-compatible avec ce qui a été fait/saisi dans le passé. 

En conséquence, les statistiques basées sur les AP & CC doivent continuer à fonctionner après les modifications. La rétro-compatibilité est un aspect essentiel du développement de Jeyser, puisque l'un des intérêts d'un CRM est justement la comparaison de l'activité des années en cours avec celles des années passées.

Donc seulement la solution 1, ajouter le support de la CE dans les statistiques existantes n'est souhaitable.

**Comment by KiDayz** [comment]
Ok c'est noté dans notre cdc. Merci 😄
