### ISSUE TITLE
Méthode pour accéder au dernier mandat

### ISSUE THREAD

**Issue by KiDayz** [n7consulting/Incipio#338]
Hello à tous, 

Dans l'optique de mettre à jour la page indicateurs afin qu'elle prenne en compte aussi bien les CC que les CE : 

Dans le fichier /home/tom/Incipio/src/Controller/Stat/IndicateursController.php, no retrouve cette méthode pour calculer le mandat en cours : 
`$mandat = $this->etudeManager->getMaxMandatCc();` 
Or on retrouve aussi la fonction : 
`$mandat = $this->etudeManager->getMaxMandat();` 
Bon, la première se base sur la date de signature des CC, la seconde se base sur la classe Etude et le mandat qui lui est associé. Le soucis avec la première, c'est qu'elle ne prend pas en compte la date de signature des CE (qui est le nouveau standard).

getMaxMandatCc est utilisé dans les graphique suivants : 
- Répartition des dépenses HT selon les comptes comptables (Mandat en cours)
- Évolution par mandat du chiffre d\'affaires signé cumulé
- Évolution par mandat du nombre d'intervenant

**Ma question** : vous paraît-il cohérent de remplacer l'appel de getMaxMandatCc par getMaxMandat (et donc finalement supprimer getMaxMandatCc, puisqu'elle n'est utilisée qu'ici), et ce afin d'unifier le support des graphiques pour la CE et la CC ?

**Comment by Stoakes** [comment]
Salut,

La question est intéressante.

Je crois me souvenir que ça avait été codé comme ça par M-Gate car ils utilisaient le champ mandat différemment de l'usage recommandé actuellement.

Pour eux mandat était le numéro de mandat. M-Gate a été créée en 2007, donc en 2016, ils remplissaient le champ mandat avec 9. Tandis qu'à N7 Consulting, mandat est le numéro de l'année de prise de fonction (donc 2016 dans notre exemple).

Je pense qu'une solution intermédiaire serait de renommer `getMaxMandatCc` en `getMaxMandatCe` et de lui faire utiliser la table CE comme référence. Ca serait backward compatible et on peut supposer que toutes les juniors ont au moins une CE de saisies (sinon c'est qu'elles n'utilisent plus Jeyser et donc pas besoin de trop s’embêter avec).

Est-ce que ça te semble cohérent ?

**Comment by KiDayz** [comment]
Yes ça me semble cohérent, parfait, merci pour ton aide ! :smile:
