### ISSUE TITLE
Junior UTC is officially joining Jeyser

### ISSUE THREAD

**Issue by KiDayz** [n7consulting/Incipio#340]
Hello everyone, 
Just a little notification to tell you that Junior UTC is officially using Jeyser in production from next monday.
Thank you for all the work that you put in Jeyser, we'll help you on that from now on.

See you soon, 
Thomas WOILLEZ

**Comment by Stoakes** [comment]
Hi,

Welcome on board ! Very happy of this news and looking forward your contributions.

Feel free to add Junior UTC logo to Jeyser homepage.  [Example](https://github.com/n7consulting/jeyser-site/commit/6a097e23d37faac2fd0c16ae1edb22cd20c561ee)

Cheers
