### ISSUE TITLE
Make a change in Jeyser DB

### ISSUE THREAD

**Issue by KiDayz** [n7consulting/Incipio#341]
Hello, 

I want to make a change in Jeyser DB by addind a "Livrable" field in the "Phase" class. 
- I have changed src/entity/Project/Phase.php by adding the variable and the set & get
-  I changed src/entity/Project/PhaseChange.php by adding the variable and the set & get
But I am lost from there, I think I want to generate a new /home/tom/Incipio/src/Migrations/Versionxxx.php file to update the DB. I am not capable of finding a way to do that by myself.
@Stoakes, any help would be useful, thank you very much !

**Comment by Stoakes** [comment]
Salut,

Le développement et la doc sont en anglais, mais pour les issues, on peut les faire en français, ça sera moins forcé, plus naturel. 😉

La commande pour générer les migrations est `docker-compose exec web bin/console doctrine:migrations:diff` (ou peut être `generate` je ne suis pas sur mon PC pour verifier rapidement).

**Comment by KiDayz** [comment]
Top merci ! :)
