### ISSUE TITLE
Pouvoir mettre des JEH non entiers dans les sous-phases

### ISSUE THREAD

**Issue by Aytoris** [n7consulting/Incipio#342]
Plusieurs JE souhaitent pouvoir mettre des JEH décimaux dans les sous-phase. Est-il possible d'autoriser cela, tout en imposant un nombre entier dans les phases ?

**Comment by KiDayz** [comment]
Hello, 
Qu'est-ce que tu appelles une sous-phase ? pour moi dans l'ERP on a des phases et des groupes (qui sont donc des groupes de phases). Corrige moi si je me trompe bien sûr.

Donc, avec cet éclairage sur la notion de phase, peux-tu préciser sur quelle entité voudrais-tu faire cela ?

**Comment by Aytoris** [comment]
L'équivalent des "sous-phases" dans ma JE sont les "phases" de Jeyser.
Nos phases sont les "groupes".
Il faudrait avoir des phases décimales mais dont la somme au sein d'un même groupe doit être entière

**Comment by KiDayz** [comment]
A voir ce qu'en pense @Stoakes, mais par exemple nous on a utilisé la représentation littérale c'est à dire que dans l'ERP pour nous une phase est l'objet Phase.
De plus je vais bientôt push pas mal de modifs sur les PVRI/PVRF et les phases, et j'ai fais les modifs sur l'objet Phase :/ 

Donc perso je suis bof chaud pour aller vers un système avec des JEHs non entières, ça peut vite amener à des erreurs... Vous avez vérifier avec la CNJE vos histoires de JEH non entières ? 😄 parce que moi pendant ma formation d'auditeurs conseils un des trucs qui revenaient le plus souvent c'était de jamais jamais avoir aucun document avec des JEHs non entières (à cause des possibles contrôles URSSAF notamment ) dans tous les documents types CE, RM, factures en tout genre. Je serais curieux d'avoir votre retour sur ça !

**Comment by Stoakes** [comment]
Je suis globalement sur la même longueur d'onde que @KiDayz sur la question des phases à JEH non entièrs, mais la discussion vaut le coup d'être lancée.

Une de mes questions est **comment est ce que ça se passe en cas d'avenant ?**
Supposons que l'on ai un groupe de 4 phases, avec chacune d'entre elle à 1.25 JEH. Si suite à un avenant seulement 2 phases sur 4 sont validées, comment est ce que ça se passe ?

Je pense que cette demande arrive parce que vous utilisez JEH comme une mesure de temps de réalisation et pas comme une unité de facturation. Et que si le groupe a un total entier de JEH, alors il est toujours possible de combiner des phases entres elles pour garder des JEH entiers.

Donc au lieu de faire

```
Développement:
 * Inscription : 1 JEH
 * Connexion: 1.5 JEH
 * Tests: 0.5 JEH
```
vous pourriez tout aussi bien faire
```
Développement:
 * Inscription : 1 JEH
 * Connexion & tests: 2 JEH
```

Dans tous les cas, c'est une modification majeure, donc ça serait bien d'avoir un peu plus de participants qui viennent discuter dans ce ticket, apporter leurs besoin et leur vision sur les phases non entières avant que l'on commence à discuter implémentation. Si vous arrivez à pinger AEI et les faire venir commenter ici, ça serait top.

**Comment by KiDayz** [comment]
Pour info et pour alimenter la disucssion, cf. l'article de Kiwi Legal sur l'indivisibilité des JEHs : 
![image](https://user-images.githubusercontent.com/42282799/108763243-74f5d200-7551-11eb-8fd3-af0f24667377.png)
