### ISSUE TITLE
Augmenter le stockage du VPS

### ISSUE THREAD

**Issue by KiDayz** [n7consulting/Incipio#344]
Hello, 

Notre ERP de prod est hébergé via un VPS sur OVH. On a atteint la limite de stockage, et on cherche à upgrader. C'est moins cher de commander un disque supplémentaire que d'upgrader le disque principal. On se demandait si il y avait des difficultés techniques liés au fait d'avoir deux disques ?
@Stoakes tu as peut-être une idée de ce qui se fait bien et de ce qui est plus compliqué ?
Merci d'avance :)

**Comment by KiDayz** [comment]
@Stoakes je me permets de te relancer car avec le problème de stockage, on est un peu bloqué avec l'erp actuellement :/

**Comment by Stoakes** [comment]
Bonsoir,

Je ne suis pas très dispo cette semaine.

Essayez de debugger d'ou vient le problème de disque. `df ` retourne 100% sur votre disque principal ou c'est seulement la limite Jeyser d'espace de stockage qui est atteinte?

Si votre disque est vraiment plain, nettoyez les images Docker inutilisées. Il y avait un problème sur les anciennes installations de Jeyser, Traefik loggait à l'intérieur du container et prenait trop de place.
Vous pouvez essayer de libérer de la place en faisant: `cd /var/www/Incipio && docker-compose rm -sf traefik && docker-compose up -d traefik`.

2 disques si vous savez gérer les points de montages, allez-y, mais ca ajoutera de la complexité dans la maintenance de votre VPS. Je suppose que la différence de prix entre les 2 options reste minime donc si c'est pour quelques euros par an, prenez la plus simple et augmentez le disque principal.

**Comment by KiDayz** [comment]
Super merci pour ton message malgré ta semaine chargée. 
Bon courage !

**Comment by KiDayz** [comment]
Si quelqu'un est sur cette issue : 
On a augmenter la capacité disque principal et modifié la variable AUTHORIZED_STORAGE_SIZE dans le fichier .env
