### ISSUE TITLE
Supprimer la dépendance au genemenu/form-bundle

### ISSUE THREAD

**Issue by Stoakes** [n7consulting/Incipio#58]
[Symfony 3]

Le genemenu form-bundle n'est plus mis à jour depuis longtemps, comporte de nombreux issues et pull request en attente.

Il n'est pas compatible Symfony 3. Il existe bien des forks, mais ils ne sont pas référencés dans packagist de manière claire et ne fonctionnent pas non plus. La meilleure solution semble d'être de se passer de ce bundle en remplacant les forms manquants par notre propre implémentation.

La solution doit cependant être étudiée plus en détails pour ne pas tomber dans un NIH syndrome.

**Comment by Stoakes** [comment]
Solution provisoire pour ne pas ralentir la migration vers Symfony 3, j'ai forké le bundle et apporté les modifications nécessaires pour le faire marcher dans nos use cases (donc uniquement les form jquery).

Les tests passent ;p

**Comment by theofidry** [comment]
👍 le fork est la meilleur option si vous voulez garder le bundle. Ça vaut le coup de re-déveloper ça en interne si ce n'est pas une partie conséquence: mieux vaut un peu de code fait maison qu'une librairie externe non maintenu qui n'est pas trop utilisé dans l'application.
