### ISSUE TITLE
Updater Symfony & PHP

### ISSUE THREAD

**Issue by theofidry** [n7consulting/Incipio#59]
Ça serait bien d'updater à Symfony 3.2 & PHP 7.1, pas mal de nouvelle features, le static typing et gros boost de perf (d'à la fois PHP & Symfony).

NB: il faudrait peut être créer un label "dette technique"

**Comment by Stoakes** [comment]
Salut,

Pour symfony 3.2, j'ai commençé ça très récemment sur la branche [symfony3-doctypes_in_fixtures](https://github.com/n7consulting/Incipio/tree/symfony3-doctypes_in_fixtures). D'après mes tests manuels, ca fonctionne quasiment partout. Il faut maintenant que j'écrive des tests avec Behat pour être sur qu'il n'y a pas de régressions entre master et la nouvelle version.

Pour la version de PHP, on parle bien de celle minimale requise dans le composer.json ? 
Je suis d'accord avec tous les arguments, mais il y a le cas de Debian pour qui aucune version de PHP7 n'est disponible sans passer par un PPA. 
Comme nous avons pas encore de code PHP7, l'imposer ne me semble pas indispensable pour le moment et je préférerais avoir à peu près les mêmes contraintes que la version de Symfony utilisée.

**Comment by theofidry** [comment]
>Pour la version de PHP, on parle bien de celle minimale requise dans le composer.json ?

Oui, et par conséquent du code de l'application lui-même

>Je suis d'accord avec tous les arguments, mais il y a le cas de Debian pour qui aucune version de PHP7 n'est disponible sans passer par un PPA.

Il y a plein d'outils comme https://github.com/phpbrew/phpbrew ou même un PPA qui le permette, n'attender pas sur la version par défaut ou le package officiel Debian qui a toujours 10ans de retard par définition. Pour info CenterOS supporte encore PHP5.3... il font ça pour une raison précise mais c'est pour un autre public, pas vous.

>Comme nous avons pas encore de code PHP7, l'imposer ne me semble pas indispensable pour le moment et je préférerais avoir à peu près les mêmes contraintes que la version de Symfony utilisée.

Symfony est un framework qui s'adresse à un public très large et à des grands compte, ils ne peuvent pas bouger aussi vite que tout le monde. PHP7.1 apporte un gros boost de performance et à mon avis, le static typing apporte énormément aussi, donc ce n'est pas indispensable mais c'est très recommander :)

Aussi à savoir: Symfony est très loin d'utiliser le static typing au sein de leur code-base, simplement parce que ça casserait leur BC promise, ce qu'ils ne peuvent pas faire. Donc les suivrent sur cette ligne de conduite ne fait pas beaucoup sense non plus.

>je préférerais avoir à peu près les mêmes contraintes que la version de Symfony utilisée.

Symfony est aussi une chose, l'ecosystème une autre: toute nouvelle libraries et beaucoup de libraries majeures passent à PHP7 en version minimale.

**Comment by Stoakes** [comment]
C'est fait.

Symfony 3.3 & PHP7.1 sur master
