### ISSUE TITLE
Migrer vers une application bundle-less

### ISSUE THREAD

**Issue by theofidry** [n7consulting/Incipio#60]
Un bundle est avant tout une glue entre du PHP-code et le framework Symfony pour exposer une configuration, routes et services. C'est utile principalement pour les *libraries*, sinon il y a déjà un bundle native: `AppKernel`. C'est pourquoi on est passé de `XBundle` et `YBundle` à `AppBundle` en Symfony 2.6 et que maintenant il est question de complètement enlever les bundles par défaut. Comment, Dashboard, Formation, Personne, etc. ne devrait pas être dans un bundle.

Bien entendu ce n'est pas une migration facile, mais ce n'est pas quelque chose qui doit être fait d'un coup et ça devrait simplifier les choses dans le futur.

**Comment by Stoakes** [comment]
Fermé en faveur de #204, migration vers Symfony 4 (qui appliquera exactement cette suggestion).
