### ISSUE TITLE
Supprimer les extensions/configuration

### ISSUE THREAD

**Issue by theofidry** [n7consulting/Incipio#61]
- http://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html
- https://phinx.org/
- https://github.com/wouterj/WouterJEloquentBundle

La commande Doctrine `schema:update` ne devrait utilisé que pour le développement ou avant une première mise en production. L'idée derrière cette command est de générer le schéma de la base de donnée depuis la configuration doctrine, *en aucun cas* assurer l'intégrité des données dans la base de donnée. Pour cela, des migrations devraient être utilisées.

**Comment by Stoakes** [comment]
Commencé il y a longtemps et achevé via #279 

Merci pour la suggestion :)
