### ISSUE TITLE
Casser les controllers

### ISSUE THREAD

**Issue by theofidry** [n7consulting/Incipio#62]
Sujet un peu plus controversé: c'est plus une question d'opinion donc à prendre comme une suggestion et non une recommendation :)

Je ne suis personnellement pas fan des *Service Locator* (i.e. `ContainerAware` classes) et des fat Controller pour les raisons suivantes:

- Un *ServiceLocator* cache les dépendances utilisées contrairement à utiliser une injection de dépendances
- Avoir pleins d'action dans un controller rend les choses confuses:
  - On ne sait plus qui dépend de quoi: un service est utilisé oui mais juste pour une action précise ou plusieurs?
  - Plus une classe est grosse moins elle est lisible. Dans certains cas il y a des avantages à regrouper tout dans une classe, mais pour moi un Controller n'en fait pas parti.

À la place je recommande d'avoir une class `*Action` pour action, i.e. casser chaque méthode des `Controller` en classes:

```
Controller/FooController
  indexAction()
  updateAction()
```

en:

```
Action/Foo/
  IndexAction
  UpdateAction
```

L'inconvénient c'est qu'il faut enregistrer ces nouvelles classes en tant que services, l'avantage c'est qu'un bundle comme https://github.com/dunglas/DunglasActionBundle facilite ça.

**Comment by Stoakes** [comment]
Après réflexion (un an ...), je ferme l'issue.

La mise à jour vers Symfony 4 va résoudre la question des dépendances et des ContainerAware.

Une ré-écriture complète de Jeyser en ADR serait un process long et fastidieux avec peu d'améliorations sur la DX,  et aucune sur l'UX. Ce n'est donc pas d'actualité.
