### ISSUE TITLE
Supprimer les managers

### ISSUE THREAD

**Issue by theofidry** [n7consulting/Incipio#63]
Les managers sont un anti-pattern:

- Le nom est trop vague: on peut mettre absolument tout et n'importe quoi, ce qui conduit à des services énormes qui ne font plus sens
- Lié au premier point: il cache des problèmes plus profond: example c'est quoi ce `EmailEtuManager#enMinusculeSansAccent()`? S'il y a un traitement de l'email à faire est-ce vraiment l'endroit pour le faire?

D'une façon générale un manager est un "quick & dirty" service un peu fourre tout qui devient vite indigeste.

Encore une fois c'est une recommendation pour le future: je ne dis pas que c'est à traiter avec la plus grande priorité.

**Comment by Stoakes** [comment]
Plus de 2 ans plus tard, je pense que l'on peut clôturer l'issue. :wink: 

Avec https://github.com/n7consulting/Incipio/pull/291, les managers sont devenus des services (même s'ils ont gardés leur nom de manager), certains ont été découpés. Il en reste quelques uns encore un peu gros mais rien qui ne puisse pas se corriger en une heure de travail, donc ce ticket n'est plus vraiment d'actualité.

Merci :100:
