### ISSUE TITLE
Utiliser PHP-CS-Fixer

### ISSUE THREAD

**Issue by theofidry** [n7consulting/Incipio#64]
Je recommande de l'utiliser avec juste un check PSR-2 et un check du header (ce qui permet de supprimer `copyright.sh`) dans un premier temps, et dans le future vous pouvez le configurer pour aller un peu plus loin.

**Comment by Stoakes** [comment]
Ok.
Je vais faire ça pour la release de la version 2.0.0 stable.

**Comment by theofidry** [comment]
Tu peux faire ça à n'importe quelle moment pas besoin d'attendre une v2 :)

**Comment by theofidry** [comment]
https://styleci.readme.io devrait faire le taff et enlever le besoin d'avoir un code sniffer
